### ISSUE TITLE
Initial repo tasks

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#1]
# Tasks when creating a new repository

## Initial files

- [ ] Docs
    - [x] README.md
    - [x] LICENSE
    - [ ] .github folder (issue template, PR template)        
- [ ] Scripts
    - [ ] Makefile
- [ ] Dependency
    - [ ] package.json

## Translations

- [ ] setup transifex

## Code validation

[ ] eslint

## Testing
- [ ] Setup karma for JS tests
- [ ] Setup UI testing

## CI

- [ ] Setup Drone
