### ISSUE TITLE
Media Viewer 1.0.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#15]
### Reason
- Initial Github release

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" #72 

### Documentation
- [ ] Doc changes: https://github.com/owncloud/docs/issues/1082

### Marketing
- [x] Ping RocketChat channel #marketing @patrickjahns 
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch https://github.com/owncloud/files_mediaviewer/issues/88 @davitol 

#### Final

- [x] Create github tag for final 'v${version}' on release branch @patrickjahns 
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [x] Smoke test tarball (at least install + enable) @patrickjahns 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details) @patrickjahns 
- [x] Publish tarball for customers (see handbook for details) @patrickjahns 
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns 

### Post-release

- [x] Rename QA milestone to '$version' @patrickjahns 
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) @patrickjahns 
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number @patrickjahns

**Comment by PVince81** [comment]
Considering that there are still some bigger changes required in the web UI, I suggest calling this 0.x.0 beta and release on Github until we reach a point where the UI is table, then we can call it 1.0.0 and release to marketplace.

Thoughts ? @felixheidecke @pmaier1 

The above release would be a Github-only release, but we can still advertise it for people to try out!

**Comment by pmaier1** [comment]
> Considering that there are still some bigger changes required in the web UI, I suggest calling this 0.x.0 beta and release on Github until we reach a point where the UI is table, then we can call it 1.0.0 and release to marketplace.

Agreed!

**Comment by felixheidecke** [comment]
@PVince81 there are a lot of checkboxes above that I'm not sure how to handle. Can you guide me thru the process?

**Comment by PVince81** [comment]
As discussed with @felixheidecke today, he'll finish the media viewer UX consolidation part (video controls well integrated with picture control) and we'll release the beta/RC later this week.

@felixheidecke in general I'm the one who goes through the checklist, but we can do it together once the time comes.

**Comment by PVince81** [comment]
Missing:

- [ ] public link capability: https://github.com/owncloud/files_mediaviewer/issues/17

**Comment by PVince81** [comment]
@felixheidecke will there be any text messages ? If yes we'll need to setup translations

**Comment by mmattel** [comment]
> The above release would be a Github-only release, but we can still advertise it for people to try out!

Question:
There is a short description in https://github.com/owncloud/files_mediaviewer#building
- could/should that be improved ?
- create a make command for ease of handling ?

**Comment by PVince81** [comment]
there is a makefile already, not sure why it's called Makefile.release. I see it has targets for local building. can we rename it ? @felixheidecke

**Comment by felixheidecke** [comment]
We sure can do that. I added https://github.com/owncloud/files_mediaviewer/pull/31 to up the version numbers for the release. We can change the name there.

**Comment by felixheidecke** [comment]
I need someone to lead me thru the process, or maybe I'll just watch someone doing it.

**Comment by PVince81** [comment]
- [ ] BUG: first video never plays: https://github.com/owncloud/files_mediaviewer/issues/37

**Comment by PVince81** [comment]
public link fixed and major bugs were fixed

another one to solve before 1.0.0, without which it would be a regression from files_videoplayer:
- [ ] fullscreen button: https://github.com/owncloud/files_mediaviewer/issues/38

**Comment by PVince81** [comment]
@pmaier1 is the description suitable for the marketplace or needs more work ?

**Comment by PVince81** [comment]
1.0.0beta here: https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.0beta

**Comment by PVince81** [comment]
feedback on beta: https://github.com/owncloud/files_mediaviewer/issues/50

**Comment by PVince81** [comment]
Remaining tasks:
- [ ] close lightbox when clicking outside: https://github.com/owncloud/files_mediaviewer/issues/53

**Comment by PVince81** [comment]
- [ ] cherry-pick changes merged to master onto the release branch

**Comment by PVince81** [comment]
RC1 here: https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.0RC1

@davitol please test

**Comment by PVince81** [comment]
assigned @phil-davis for manually ~~breaking~~ testing this app

**Comment by PVince81** [comment]
- [ ] BUG: preloaded images are not hidden properly in Firefox with owncloud-enterprise-complete apps: https://github.com/owncloud/files_mediaviewer/issues/68

**Comment by PVince81** [comment]
- [ ] BUG: some perf issues, preloading too many videos: https://github.com/owncloud/files_mediaviewer/issues/69

**Comment by PVince81** [comment]
RC2: https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.0RC2

**Comment by PVince81** [comment]
raised https://github.com/owncloud/docs/issues/1082 for doc changes

**Comment by skshetry** [comment]
`files_mediaviewer` testplan for 1.0.0RC2
Issue - #72 
Test plan in QA repo - owncloud/QA#619 and owncloud/QA#620

**Comment by micbar** [comment]
Ok, we have remaining Issues, but according to PM we need to release now.

Let's go FINAL

**Comment by davitol** [comment]
> we have remaining Issues

List of known issues in RC4: https://github.com/owncloud/files_mediaviewer/issues/88#issuecomment-508674043

**Comment by micbar** [comment]
@davitol Thank you. They are known limitations for the first release.

**Comment by davitol** [comment]
@felixheidecke Seen you close the ticket (i guess it is due to version was already released) but we should not forge that documentation needed hasn't been updated yet: https://github.com/owncloud/docs/issues/1082
