### ISSUE TITLE
Files mediaviewer 1.0.2

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/files_mediaviewer#192]
### Reason

- [x] Release needed for https://github.com/owncloud/files_mediaviewer/issues/35
- [x] https://github.com/owncloud/files_mediaviewer/pull/194, https://github.com/owncloud/files_mediaviewer/pull/196, https://github.com/owncloud/files_mediaviewer/pull/186, https://github.com/owncloud/files_mediaviewer/pull/200

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "1.0.2 Testplan"  @davitol  https://github.com/owncloud/files_mediaviewer/issues/195

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs. https://github.com/owncloud/docs/issues/2448

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending https://github.com/owncloud/docs/issues/2448
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol files_mediaviewer is available for testing https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.2RC1

**Comment by HanaGemela** [comment]
@davitol please run regression test to ensure everything works https://github.com/owncloud/files_mediaviewer/pull/186#pullrequestreview-366245363

**Comment by mmattel** [comment]
@HanaGemela #200 (a security PR) needs to be approved and merged by you. That one should also be part of the regression test

**Comment by phil-davis** [comment]
I merged #200 to the release branch just now.

@HanaGemela please make a new RC for @davitol to test.

**Comment by HanaGemela** [comment]
@davitol RC2 available in https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.2RC2

**Comment by davitol** [comment]
@HanaGemela IMHO we should document somewhere that https://github.com/owncloud/files_mediaviewer/pull/194 does not work for Chrome browser, but ok for Safari and Mozilla

**Comment by davitol** [comment]
@HanaGemela also https://github.com/owncloud/files_mediaviewer/pull/194 item is not included in the changelog file. We should add it.

**Comment by HanaGemela** [comment]
@davitol Thank you, I've created https://github.com/owncloud/docs/issues/2448

**Comment by HanaGemela** [comment]
@davitol #194 is not part of the current release. #196 is and it is also in the changelog

**Comment by davitol** [comment]
> @davitol #194 is not part of the current release. #196 is and it is also in the changelog

As checked https://github.com/owncloud/files_mediaviewer/pull/196 is not included in RC2 tarball Changelog file. Please add that item in RC3/final tarball

**Comment by davitol** [comment]
@HanaGemela Tarball is QA-ready

> @davitol RC2 available in https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.2RC2

**Comment by HanaGemela** [comment]
@davitol I've build the final https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.2
please check the changelog and sanity test

**Comment by davitol** [comment]
> @davitol I've build the final https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.2
> please check the changelog and sanity test

LGTM :shipit:

**Comment by HanaGemela** [comment]
Waiting for documentation before publishing (cc @settermjd)
