### ISSUE TITLE
Tracking testing results for Files Mediaviewer 1.0.3.

### ISSUE THREAD

**Issue by davitol** [owncloud/files_mediaviewer#271]
Changelog

### Added

- [x] Update config.json to support mimetype video/quicktime - [#194](https://github.com/owncloud/files_mediaviewer/issues/194)
- [x] Add time display to viewer controls - [#225](https://github.com/owncloud/files_mediaviewer/issues/225)
- [x] Add l10n support - [#217](https://github.com/owncloud/files_mediaviewer/issues/217) l10n folder is not present in the RC1 tarball

**Comment by davitol** [comment]
Final is already released. Sanity tested and LGTM. Let's close this ticket
