### ISSUE TITLE
Release files_mediaviewer 1.0.5

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_mediaviewer#401]
PR #400 "[Security] Bump y18n from 4.0.0 to 4.0.3"
PR #407 "[Security] Bump ssri from 6.0.1 to 6.0.2"
PR #532 "Bump kind-of from 6.0.2 to 6.0.3"
PR #542 "Bump webpack-cli from 4.8.0 to 4.9.1"
PR #546 "Bump style-loader from 3.2.1 to 3.3.1"
PR #551 "Bump sass from 1.38.2 to 1.43.4"
PR #552 "Bump css-loader from 6.2.0 to 6.5.0"
PR #553 "Bump swiper from 7.0.2 to 7.2.0"
PR #554  "Bump webpack from 5.51.1 to 5.61.0"
PR #555 "Bump svelte from 3.42.4 to 3.44.1"
PR #556 "Bump @babel/preset-env from 7.15.0 to 7.16.0"
PR #557 "Bump @babel/core from 7.15.0 to 7.16.0"
PR #548 "[l10n] translations make, extract wrong texts for js files"
PR #558 "Fix l10n processing"

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> #533 
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [ ] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Test and document in testplan + manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [ ] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [ ] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [ ] Do changelog tests
    - [ ] Do regression tests
    - [ ] smoke test with docker image `owncloud/server:latest`
    - [ ] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue #533

**Comment by mmattel** [comment]
Another Security Bump #407

**Comment by jnweiger** [comment]
We have a transifex commit coming in here really every day. Its this sane?

**Comment by phil-davis** [comment]
Transifex is pushing a commit every day that only updates the `POT-Creation-Date`
https://github.com/owncloud/files_mediaviewer/commit/28138083d69fb44c36e800452d7adbf94a537b4e

That is not sane. It does not happen in other repos. I am not familiar with the Transifex setups - there must be a setting "somewhere on the internet" to stop that happening.

Library bumps: they are JavaScript things. Maybe some JS developer could look and see if there is anything that obviously should not be done. Then we merge everything and manually check the app.

**Comment by micbar** [comment]
It was created by Florian Lenz. Currently no active maintainer. Needs to be handled by server team

**Comment by JanAckermann** [comment]
**Done**

**Comment by jnweiger** [comment]
@JanAckermann files_mediaviewer does not have `sonar-project.properties`
Please add that file to my release-1.0.5 branch if needed? Will be merged to master after the release.

**Comment by jnweiger** [comment]
## Remaining issues from 1.0.4 

* [ ] Not fixed, reopening #337 - Text and icon in file actions menu is missing
* [ ] reproduced, reopening #320 - Gallery overview is missing 
* [ ] reproduced #318 - Browse large images with zoom 
* [ ] new issue #350 - [QA] video scrubber and control panel overlap with video
* [ ] new issue #351 - [QA] clicking a video shows it paused
* [ ] new issue #352 - [QA] The spacebar cannot toggle pause/play when in fullscreen mode
* [ ] new issue #353 - [QA] no helpful message when opening unsupported video type
* [ ] new issue #354 - [QA] Video type ogv is recognized, but not ogg or ogx
* [ ] new issue #355 - [QA] fails with IE11
* [ ] new issue #356 - [QA] Audio files do not play

## new issues in 1.0.5

* [ ] ...

**Comment by JanAckermann** [comment]
>Not fixed, reopening Text and icon in file actions menu is missing #337 - Text and icon in file actions menu is missing

Texts should be there at least?!

**Comment by jnweiger** [comment]
> > Not fixed, reopening Text and icon in file actions menu is missing #337 - Text and icon in file actions menu is missing
> 
> Texts should be there at least?!

Yep. Texts and icons are there. But english texts only. Reopening #337 again, back in dev.

**Comment by jnweiger** [comment]
Back in dev, I believe https://github.com/owncloud/files_mediaviewer/issues/337#issuecomment-965487187 needs a fix.

**Comment by GeraldLeikam** [comment]
close after release
